apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-controller
rules:
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs: [ "get", "list", "watch" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-controller
  namespace: controller-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-controller
subjects:
  - kind: ServiceAccount
    name: simple-controller
    namespace: controller-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-controller-deployment
  namespace: controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-controller
  template:
    metadata:
      labels:
        app: simple-controller
    spec:
      containers:
        - name: simple-controller
          image: togettoyou/simple-controller:latest
          imagePullPolicy: IfNotPresent
      serviceAccountName: simple-controller
