apiVersion: v1
kind: Secret
metadata:
  name: simple-aa-server-cert
  namespace: aa-system
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-tls-cert>
  tls.key: <base64-encoded-tls-key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-aa-server-deployment
  namespace: aa-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-aa-server
  template:
    metadata:
      labels:
        app: simple-aa-server
    spec:
      containers:
        - name: simple-aa-server
          image: togettoyou/simple-aa-server:latest
          imagePullPolicy: IfNotPresent
          args:
            - --tls-crt-file=/etc/aa/certs/tls.crt
            - --tls-key-file=/etc/aa/certs/tls.key
            - --port=443
          volumeMounts:
            - name: cert
              mountPath: "/etc/aa/certs"
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: simple-aa-server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: simple-aa-server
  namespace: aa-system
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: simple-aa-server
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.simple.aa.io
spec:
  group: simple.aa.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    namespace: aa-system
    name: simple-aa-server
    port: 443
  caBundle: <base64-encoded-ca-cert>
