apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-scheduler-extender
  namespace: scheduler-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-scheduler-extender
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: simple-scheduler-extender
    namespace: scheduler-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-scheduler-extender
  namespace: scheduler-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: simple-scheduler
    extenders:
      - urlPrefix: "http://localhost:8080"
        filterVerb: filter
        prioritizeVerb: prioritize
        preemptVerb: preempt
        # bindVerb: bind
        enableHTTPS: false
        httpTimeout: 30s
        weight: 1
        nodeCacheCapable: false
        managedResources: [ ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-scheduler-extender-deployment
  namespace: scheduler-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-scheduler-extender
  template:
    metadata:
      labels:
        app: simple-scheduler-extender
    spec:
      containers:
        - name: kube-scheduler
          image: registry.k8s.io/kube-scheduler:v1.27.2
          imagePullPolicy: IfNotPresent
          command:
            - kube-scheduler
            - --config=/etc/kubernetes/config.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kubernetes
        - name: simple-scheduler-extender
          image: togettoyou/simple-scheduler-extender:latest
          imagePullPolicy: IfNotPresent
      serviceAccountName: simple-scheduler-extender
      volumes:
        - name: config-volume
          configMap:
            name: simple-scheduler-extender
