# permissions for end users to view mypods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mypod-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple
    app.kubernetes.io/part-of: simple
    app.kubernetes.io/managed-by: kustomize
  name: mypod-viewer-role
rules:
- apiGroups:
  - simple.controller.io
  resources:
  - mypods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simple.controller.io
  resources:
  - mypods/status
  verbs:
  - get
