{
 "title": "Kubernetes 节点资源监控",
 "tags": [
  "Kubernetes",
  "kube-state-metrics",
  "Prometheus",
  "Node exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   { "name": "interval", "label": "时间间隔", "query": "5s, 15s, 30s, 1m, 2m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "全局概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes 资源统计",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "Nodes"
    },
    { "expr": "count(kube_namespace_created)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "count(kube_deployment_created)", "legendFormat": "Deployments" },
    {
     "expr": "count(kube_statefulset_created)",
     "legendFormat": "Statefulsets"
    },
    { "expr": "count(kube_daemonset_created)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_horizontalpodautoscaler_info)",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    {
     "expr": "count(kube_networkpolicy_created)",
     "legendFormat": "Network Policies"
    }
   ]
  },
  {
   "title": "Pod 列表",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    { "expr": "kube_pod_info" }
   ]
  },
  {
   "title": "节点列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "kube_node_info - 0", "legendFormat": "__auto" },
    {
     "expr": "sum(time() - node_boot_time_seconds)by(node)/86400",
     "legendFormat": "运行天数"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)by(node)",
     "legendFormat": "内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"}) by (node)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"}) by (node)",
     "legendFormat": "磁盘"
    },
    {
     "expr": "avg(sum by (node, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval]))) by(node)",
     "legendFormat": "CPU 利用率"
    },
    {
     "expr": "sum (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by(node) / sum(node_memory_MemTotal_bytes) by(node)",
     "legendFormat": "内存利用率"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext.*\"}) by(node) / sum(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"}) by(node)",
     "legendFormat": "磁盘利用率"
    },
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"} - 0",
     "legendFormat": "状态"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "节点 CPU 使用量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "核" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "已用"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\",node=\"$node\"})",
     "legendFormat": "总核数"
    }
   ]
  },
  {
   "title": "节点 CPU 利用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",node=\"$node\"}[$__rate_interval])))",
     "legendFormat": "CPU 利用率"
    }
   ]
  },
  {
   "title": "节点 CPU 使用明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{node=\"$node\"}[$__rate_interval])) by (mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "节点 CPU 平均负载",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{node=\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{node=\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{node=\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Pod CPU 使用量",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "核" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval])) by (namespace,pod,container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Throttled 节流预测",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval])) / sum by (namespace,pod,container)(kube_pod_container_resource_limits{node=\"$node\", resource=\"cpu\"}) > 0.8",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "节点内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\"} - node_memory_MemAvailable_bytes{node=\"$node\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\"}",
     "legendFormat": "总内存"
    }
   ]
  },
  {
   "title": "节点内存利用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{node=\"$node\"} - node_memory_MemAvailable_bytes{node=\"$node\"}) / (node_memory_MemTotal_bytes{node=\"$node\"})",
     "legendFormat": "内存利用率"
    }
   ]
  },
  {
   "title": "节点内存使用明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\"} - node_memory_MemFree_bytes{node=\"$node\"} - (node_memory_Cached_bytes{node=\"$node\"} + node_memory_Buffers_bytes{node=\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_Cached_bytes{node=\"$node\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=\"$node\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"$node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{node=\"$node\"} - node_memory_SwapFree_bytes{node=\"$node\"}",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{node=\"$node\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  {
   "title": "Pod OOM 预测",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container)(container_memory_working_set_bytes{instance=\"$node\", image!=\"\", container!=\"\"}) / sum by (namespace,pod,container)(kube_pod_container_resource_limits{node=\"$node\", resource=\"memory\"}) > 0.8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod 内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"$node\", image!=\"\", container!=\"\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"$node\", image!=\"\", container!=\"\"}) by (namespace,pod,container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "磁盘", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "节点磁盘使用量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"xfs|ext.*\",node=\"$node\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext.*\",node=\"$node\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"xfs|ext.*\",node=\"$node\"}",
     "legendFormat": "总磁盘量"
    }
   ]
  },
  {
   "title": "节点磁盘利用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\",node=\"$node\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext.*\",node=\"$node\"}) / (node_filesystem_size_bytes{fstype=~\"xfs|ext.*\",node=\"$node\"})",
     "legendFormat": "磁盘利用率"
    }
   ]
  },
  {
   "title": "节点磁盘使用明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{node=\"$node\"} - node_filesystem_free_bytes{node=\"$node\"})) / (node_filesystem_size_bytes{node=\"$node\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "节点磁盘读取 IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "read/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Pod 磁盘读取速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval])) by (device)",
     "legendFormat": "All {device=\"{{ device }}\"}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval])) by (namespace,pod,container,device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点磁盘读取速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "节点磁盘写入 IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "write/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Pod 磁盘写入速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval])) by (device)",
     "legendFormat": "All {device=\"{{ device }}\"}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=\"$node\", image!=\"\", container!=\"\"}[$__rate_interval])) by (namespace,pod,container,device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点磁盘写入速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "节点带宽上传速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "All_Out"
    }
   ]
  },
  {
   "title": "Pod 带宽上传速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"$node\", image!=\"\"}[$__rate_interval])) by (namespace,pod,interface)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点带宽下载速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "All_In"
    }
   ]
  },
  {
   "title": "Pod 带宽下载速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"$node\", image!=\"\"}[$__rate_interval])) by (namespace,pod,interface)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点出包量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "All_Out"
    }
   ]
  },
  {
   "title": "Pod 出包量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{instance=\"$node\", image!=\"\"}[$__rate_interval])) by (namespace,pod,interface)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点入包量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum(rate(node_network_receive_packets_total{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "All_In"
    }
   ]
  },
  {
   "title": "Pod 入包量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{instance=\"$node\", image!=\"\"}[$__rate_interval])) by (namespace,pod,interface)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}